name: Rust CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
      
    - name: Build (NetCDF only)
      run: cargo build --no-default-features --features netcdf
      
    - name: Build (with Zarr)
      run: cargo build --all-features
      
    - name: Test (NetCDF only)
      run: cargo test --no-default-features --features netcdf
      
    - name: Test (with Zarr)
      run: cargo test --all-features
      
    - name: Build documentation
      run: cargo doc --all-features --no-deps

  minimal:
    name: Minimal Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Check minimal build
      run: cargo check --no-default-features
